server:
  port: 8086

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Vivek273165}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-saga-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "orderCreatedEvent:com.ecommerce.orderservice.kafka.event.OrderCreatedEvent,orderCancelledEvent:com.ecommerce.orderservice.kafka.event.OrderCancelledEvent,inventoryReservedEvent:com.ecommerce.orderservice.kafka.event.InventoryReservedEvent,inventoryFailedEvent:com.ecommerce.orderservice.kafka.event.InventoryFailedEvent,paymentCompletedEvent:com.ecommerce.orderservice.kafka.event.PaymentCompletedEvent,paymentFailedEvent:com.ecommerce.orderservice.kafka.event.PaymentFailedEvent"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET:MySecretKeyForEcommerceApplication2026MySecretKey}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      cartService:
        baseConfig: default
      inventoryService:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      cartService:
        baseConfig: default
      inventoryService:
        baseConfig: default

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
